// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC-7-JR3J1QBsXNIh_MIZ7THfw0WGjSpU',
    appId: '1:995525214:ios:8d4e4e8cc44909e8966acf',
    messagingSenderId: '995525214',
    projectId: 'youth-opportunity-hub',
    storageBucket: 'youth-opportunity-hub.firebasestorage.app',
    iosBundleId: 'com.example.youthHubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC-7-JR3J1QBsXNIh_MIZ7THfw0WGjSpU',
    appId: '1:995525214:ios:8d4e4e8cc44909e8966acf',
    messagingSenderId: '995525214',
    projectId: 'youth-opportunity-hub',
    storageBucket: 'youth-opportunity-hub.firebasestorage.app',
    iosBundleId: 'com.example.youthHubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5SvHPjTg1A3A6blZAC1w0LnvewDctAYw',
    appId: '1:995525214:web:33e3065b7e10e45b966acf',
    messagingSenderId: '995525214',
    projectId: 'youth-opportunity-hub',
    authDomain: 'youth-opportunity-hub.firebaseapp.com',
    storageBucket: 'youth-opportunity-hub.firebasestorage.app',
    measurementId: 'G-JJVRR0N4B3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5SvHPjTg1A3A6blZAC1w0LnvewDctAYw',
    appId: '1:995525214:web:15a6921a36f88a7a966acf',
    messagingSenderId: '995525214',
    projectId: 'youth-opportunity-hub',
    authDomain: 'youth-opportunity-hub.firebaseapp.com',
    storageBucket: 'youth-opportunity-hub.firebasestorage.app',
    measurementId: 'G-26JS3N85EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzASaXEfNFhf7bmiJB7dOw9esOiie5yXo',
    appId: '1:995525214:android:58ae97ce1e7afb56966acf',
    messagingSenderId: '995525214',
    projectId: 'youth-opportunity-hub',
    storageBucket: 'youth-opportunity-hub.firebasestorage.app',
  );
}
